### ISSUE TITLE
The triple eval is not needed :-) 

### ISSUE THREAD

**Issue by RobTrew** [ksalzke/estimate-total-time-omnifocus-plugin#1]
eval is seldom a good plan (strongly deprecated from every direction :-), and where you have:

```
var conditionsArray = [
      eval(selection.tasks.length > 0),
      eval(selection.projects.length > 0),
      eval(selection.tags.length > 0),
    ];
    return conditionsArray.includes(true);
```

its probably worth taking a look at the built-in Array methods  `.some()` and `.every()`.

Here, for example, you could write things like:

```javascript
[
    selection.tasks,
    selection.projects,
    selection.tags
].some(x => x.length > 0);
```

or if you prefer:

```javascript
["tasks", "projects", "tags"].some(
    k => selection[k].length > 0
);
```

**Comment by ksalzke** [comment]
Thanks @RobTrew. It took me a while to get to it but I've now adjusted it to `return selection.tasks.length > 0 || selection.projects.length > 0 || selection.tags.length > 0`. Can you see any issue with this?

**Comment by RobTrew** [comment]
That looks good :-)

(Incidentally, the .some method is also 'short-circuiting' – like the evaluation of enchained (||) expressions. 

But I can understand the appeal of restricting the lexicon of the idiom – there are certainly good arguments for that.
