### ISSUE TITLE
I get twice the amount of time

### ISSUE THREAD

**Issue by woodyc79** [ksalzke/estimate-total-time-omnifocus-plugin#4]
Hello! First: Thank you very much for the effort you put into this!

Currently - with intended tasks i get twice the time that should be alerted:
![image](https://user-images.githubusercontent.com/1710712/111129373-509c7c80-8576-11eb-99a0-e05788a912a4.png)

Thank you

**Comment by ksalzke** [comment]
Hi @woodyc79! Thanks for this, and thanks for your patience in awaiting a response from me—I've just had a baby so I've been a tad distracted.

What was happening was that the plugin was counting the selected project and any selected tasks separately. I've just now pushed an updated script that should avoid any tasks being double-counted.

I hope this (somewhat belatedly) helps!
